#pragma once

#define EVENT_QUERY_STATE       0x0001
#define EVENT_MODIFY_STATE      0x0002

#define EVENT_GENERIC_READ EVENT_QUERY_STATE | READ_CONTROL
#define EVENT_GENERIC_WRITE EVENT_MODIFY_STATE | READ_CONTROL
#define EVENT_GENERIC_EXECUTE READ_CONTROL | SYNCHRONIZE

#define EVENT_ALL_ACCESS EVENT_QUERY_STATE | EVENT_MODIFY_STATE | DELETE | \
                         READ_CONTROL | WRITE_DAC | WRITE_OWNER | SYNCHRONIZE

typedef struct {
    sync_object header;
    EVENT_TYPE type;
    spinlock_t lock;
} event_object;
